[versions]
min-sdk = "23"
target-sdk = "36"
compile-sdk = "36"

agp = "9.0.0"
kotlin = "2.3.0"
workmanager = "2.8.1"
serialization = "1.9.0"
koin = "4.1.1"

accompanist = "0.36.0"
compose = "1.10.1"
camerax = "1.5.2"


[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
alp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ks = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmm = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jc = { id = "org.jetbrains.compose", version = "1.11.0-alpha01" }
cc = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
# kotlin
# https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.9.0"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"

# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Google
google-material = "com.google.android.material:material:1.13.0"
google-barcode = "com.google.mlkit:barcode-scanning:17.3.0"
google-accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
google-accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

# AndroidX
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.2.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.12.2"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.8.9"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.4.1"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.9.6"
androidx-startup-runtime = "androidx.startup:startup-runtime:1.2.0"

# Camera
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }


# Compose
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.8"
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
